# Generated by Django 2.1.1 on 2018-09-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_maker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TripStops',
            new_name='TripStop',
        ),
    ]
