# Generated by Django 2.1.1 on 2018-10-24 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_maker', '0003_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='rating',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
