# Generated by Django 2.1.1 on 2018-10-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_maker', '0004_auto_20181024_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='stop_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
