# Generated by Django 2.1.2 on 2018-10-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_maker', '0005_tripstop_stop_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
