# Generated by Django 2.1.2 on 2018-10-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_maker', '0008_auto_20181026_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='google_maps_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='place',
            name='place_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
